# Display Beep
print(" ##########")
print("## 0    0 ##")
print("## \\____/ ##")
print(" ##########")
print("     ##    ")
print(" ##########")
print("## ------ ##")
print("## 0\"     ##")
print("##        ##")
print("##        ##")
print(" #        #")
print(" ##########")